discord:
  token: "CHANGE_ME"
  status:
    text: "FURIA Compendium chatbot"
    activity: "WATCHING" # "PLAYING", "LISTENING", "WATCHING", "COMPETING"

telegram:
  token: "CHANGE_ME"

openai:
  token: "CHANGE_ME"
  model: "gpt-4o-search-preview" # It's advised to use a model that supports search
  systemMessage: |
    Voc√™ √© um assistente especializado no time de E-Sports FURIA.
    S√≥ pode responder perguntas relacionadas √† FURIA: jogadores, partidas, campeonatos, jogos... tudo que envolva a equipe. 
    Qualquer outra pergunta deve ser recusada com educa√ß√£o. Use um tom informal e amig√°vel. Seja direto, mas simp√°tico. 
    Voc√™ est√° atendendo o ${user}, n√£o ultrapassar 1024 caracteres.

  maxCharacters: 1024

chatbotText:
  tooManyCharacters: "A resposta √© muito longa. Tente perguntar de outra forma ou fa√ßa uma pergunta mais espec√≠fica."
  tooManyRequests: "Estou com dificuldades para responder. Tente novamente mais tarde."
  genericError: "Upss! Ocorreu um erro. Tente novamente mais tarde."
  startMessage: | 
    Faala Furioso! Eu sou o assistente da FURIA!!! üêæ
    Eu posso te ajudar com informa√ß√µes sobre o time como jogadores, partidas, at√© mesmo onde assistir, ou te dizer onde comprar uma camiseta! 
    √â s√≥ me contar o que precisa!